### ISSUE TITLE
Is node-trueskill usable from Javascript?

### ISSUE THREAD

**Issue by marcolino** [freethenation/node-trueskill#1]
This is not a real issue, sorry...
I would like to use your trueskill algorithm in an angularjs app...
Is it possible? I suppose it's not, since you use require("trueskill") ...

Otherwise, should it posssible to use it as a node service?

TIA!

**Comment by richardklafter** [comment]
One option is to use browserify! http://browserify.org/

 "node-trueskill" is pure JS and its only dependency is "free-gaussian" which is also pure JS so it should not be hard to make the library run in a browser by manually pasting together a few libraries if you would rather go that route.

**Comment by marcolino** [comment]
Thanks! I did never heard about browserify... Will give it a try..

**Comment by marcolino** [comment]
I did finally test node-trueskill with browserify, and it works just fine.
However ... any plan to create a bower package? :-)

**Comment by richardklafter** [comment]
Nope. I will gladly accept pull requests tough :)
