### ISSUE TITLE
Is node-trueskill usable for *team* matches?

### ISSUE THREAD

**Issue by marcolino** [freethenation/node-trueskill#2]
Trueskill algorithm from Microsoft fits _team_ matches, not only single player ones) (see http://boson.research.microsoft.com/trueskillranking/rankcalculator.aspx).
Does your implementation allows this scenario?
If yes, can you please document it someway? (a simple example on the README should be great...)

**Comment by freethenation** [comment]
I did not need it for my use case. There is a comment in the code that addresses team matches.

``` python
  # Create all the variable nodes in the graph.  "Teams" are each a
  # single player; there's a one-to-one correspondence between players
  # and teams.  (It would be straightforward to make multiplayer
  # teams, but it's not needed for my current purposes.)
```

If you end up adding it I would gladly check your work (math can be a lil tricky) and/or accept a pull request.

**Comment by marcolino** [comment]
I see... Sorry, I missed your comment on coffe source. Unfortunately I find math behind Trueskill _quite_ tricky... And, I don't use coffescript for everyday work... However I'll watch this project, if somebody will implement team matches... :-)
