### ISSUE TITLE
Adding a second game?

### ISSUE THREAD

**Issue by andrewbrereton** [freethenation/node-trueskill#5]
Hi, thanks for this. I am creating a leaderboard and I'm wondering the proper way to add multiple games.

At the moment, I'm appending the results of the second game to the players `rank` value.

Is this correct?

**Comment by richardklafter** [comment]
Ya just update players ranks and call `trueskill.AdjustPlayers` for each additional game

**Comment by andrewbrereton** [comment]
Perfect, thanks.
